Refactored navbar for horizontal viewing
devalparikh/Findr pull request #44
Opened 2021-02-07 20:53 UTC by alexandrofuentelzas

- Navbar height changed from 55px to 75px for desktop view (inconsistent heights between mobile and desktop)
- styled navbar for horizontal view as well
- media query capped at 950 px (previously 790px) to prevent inner navbar components from colliding
- commented out the 0.2s transition from navBarClosed class for snappier animation
- Added simple logic to navbar Findr logo so that hamburger button and navbar closes when the Findr logo is pressed while the navbar is open
- All NavLinks are still present for testing purposes but in a later commit I can adjust the navlinks to have only the required buttons

2021-02-08 18:42 UTC, jersteve requested changes
Hello sir, great job except put the nav bar size of desktop back to normal since it looks too big. other than that, you fixed the search bar issue so good job.

2021-02-08 18:50 UTC, jersteve approved these changes

2021-02-08 20:04 UTC, alexandrofuentelzas commented on frontend/src/App.css
> +@media (max-width:950px) {
Changed this to 950px to align with the navbar 950px change as well. This will change the entire horizontal view for Findr to a cleaner view.

2021-02-08 20:05 UTC, jersteve approved these changes
looks good...

2021-02-09 01:21 UTC, devalparikh approved these changes
smooth work much needed changes

2021-02-09 01:21 UTC, devalparikh commented on frontend/src/components/navbar/Navbar.tsx
> +  const MAX_SCREEN_WIDTH = 950;
I like this practice!! Let's all start doing this with predefined values like this @jersteve @alexandrofuentelzas

2021-02-09 01:22 UTC, merged